name: Weekly Multi-Platform Build

on:
  schedule:
    - cron: '0 0 * * MON'   # every Monday at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore Jammy.Main

      - name: Build Windows
        run: dotnet build Jammy.Main --configuration Release --no-restore

      - name: Publish Windows binary
        run: dotnet publish Jammy.Main -c Release -r win-x64 -o out/win /p:EnableWindowsTargeting=true /p:DebugType=None /p:DebugSymbols=false --self-contained true

      - name: Zip Windows binary
        shell: powershell
        run: |
          Copy-Item -Path "games" -Destination "out/win/games" -Recurse
          Copy-Item -Path "roms" -Destination "out/win/roms" -Recurse
          Compress-Archive -Path out/win/* -DestinationPath Jammy-windows.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v6
        with:
          name: Jammy-windows
          path: Jammy-windows.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore Jammy.Main.Linux

      - name: Build Linux
        run: dotnet build Jammy.Main.Linux --configuration Release --no-restore

      - name: Publish Linux binary
        run: dotnet publish Jammy.Main.Linux -c Release -r linux-x64 -o out/linux /p:DebugType=None /p:DebugSymbols=false --self-contained true

      - name: Zip Linux binary
        run: |
          cp -r games out/linux/games
          cp -r roms out/linux/roms
          tar -czf Jammy-linux.tar.gz -C out/linux .

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v6
        with:
          name: Jammy-linux
          path: Jammy-linux.tar.gz

  create-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v6
        with:
          name: Jammy-windows

      - name: Download Linux Artifact
        uses: actions/download-artifact@v6
        with:
          name: Jammy-linux

      - name: Upload to draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-build
          name: Latest Build (Draft)
          draft: true
          prerelease: true
          files: |
            Jammy-windows.zip
            Jammy-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
