name: Manual Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Download assets from the latest-build draft release
      - name: Download latest-build assets
        uses: robinraju/release-downloader@v1.8
        with:
          tag: latest-build
          fileName: "*"
          out-file-path: ./downloads
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename files with run number
        run: |
          mv ./downloads/Jammy-0.0.1-windows.zip ./downloads/Jammy-${{ github.run_number }}-windows.zip
          mv ./downloads/Jammy-0.0.1-linux.zip ./downloads/Jammy-${{ github.run_number }}-linux.zip

      - name: Create Windows Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: windows-${{ github.run_number }}
          name: Jammy Windows Release ${{ github.run_number }}
          files: ./downloads/Jammy-${{ github.run_number }}-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Linux Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: linux-${{ github.run_number }}
          name: Jammy Linux Release ${{ github.run_number }}
          files: ./downloads/Jammy-${{ github.run_number }}-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
